## Colors configuration
colors:
  # Default colors
  primary:
    background: '#0c1018'
    foreground: '#f1c4c0'

  # Normal colors
  normal:
    black:   '#20242C'
    red:     '#F8506D'
    green:   '#F06576'
    yellow:  '#DD4157'
    blue:    '#FD4955'
    magenta: '#E9698E'
    cyan:    '#EA7288'
    white:   '#782831'

  # Bright colors
  bright:
    black:   '#a88986'
    red:     '#F8506D'
    green:   '#F06576'
    yellow:  '#DD4157'
    blue:    '#FD4955'
    magenta: '#E9698E'
    cyan:    '#EA7288'
    white:   '#782831'
