#####################################
#                                   #
#  @author      : 00xWolf           #
#    GitHub    : @mmsaeed509       #
#    Developer : Mahmoud Mohamed   #
#  﫥  Copyright : Exodia OS         #
#                                   #
#####################################

# Colors configuration #
[colors.primary]
background = '#090a0a'
foreground = '#dfe1e1'

# Normal colors #
[colors.normal]
black   = '#191c1c'
red     = '#247270'
green   = '#2A817E'
yellow  = '#2E908D'
blue    = '#35A9A4'
magenta = '#4AB3B0'
cyan    = '#9BADAC'
white   = '#dfe1e1'

# Bright colors #
[colors.bright]
black   = '#9c9d9d'
red     = '#247270'
green   = '#2A817E'
yellow  = '#2E908D'
blue    = '#35A9A4'
magenta = '#4AB3B0'
cyan    = '#9BADAC'
white   = '#dfe1e1'
