## Colors configuration
colors:
  # Default colors
  primary:
    background: '#1a1f26'
    foreground: '#0abdc6'

  # Normal colors
  normal:
    black:   '#0C1832'
    red:     '#AC0000'
    green:   '#9c0598'
    yellow:  '#949204'
    blue:    '#0b35a3'
    magenta: '#6f02a3'
    cyan:    '#02a39d'
    white:   '#a9a9ab'

  # Bright colors
  bright:
    black:   '#1c3875'
    red:     '#e80707'
    green:   '#ff00f8'
    yellow:  '#FFFC04'
    blue:    '#1151F9'
    magenta: '#a005eb'
    cyan:    '#02FFF5'
    white:   '#DCDBE0'
