#####################################
#                                   #
#  @author      : 00xWolf           #
#    GitHub    : @mmsaeed509       #
#    Developer : Mahmoud Mohamed   #
#  﫥  Copyright : Exodia OS         #
#                                   #
#####################################

# Colors configuration #
[colors.primary]
background = '#101419'
foreground = '#cc02f5'

# Normal colors #
[colors.normal]
black   = '#000000'
red     = '#b081e5'
green   = '#9658dd'
yellow  = '#7d2fd5'
blue    = '#6523b0'
magenta = '#752fc4'
cyan    = '#4f1e87'
white   = '#3c1469'

# Bright colors #
[colors.bright]
black   = '#61038f'
red     = '#C874F2'
green   = '#A519EA'
yellow  = '#6D00A2'
blue    = '#BC4FF2'
magenta = '#B741F2'
cyan    = '#B12FF2'
white   = '#594384'
