## Colors configuration
colors:
  # Default colors
  primary:
    background: '#101419'
    foreground: '#cc02f5'

  # Normal colors
  normal:
    black:   '#2F0046'
    red:     '#C874F2'
    green:   '#A519EA'
    yellow:  '#6D00A2'
    blue:    '#BC4FF2'
    magenta: '#B741F2'
    cyan:    '#B12FF2'
    white:   '#594384'

  # Bright colors
  bright:
    black:   '#BD3BFD'
    red:     '#070283'
    green:   '#9100a6'
    yellow:  '#ff0064'
    blue:    '#0254C1'
    magenta: '#00FE66'
    cyan:    '#32FF00'
    white:   '#A1271A'
