## Colors configuration
colors:
  # Default colors
  primary:
    background: '#26122C'
    foreground: '#D78FFE'

  # Normal colors
  normal:
    black:   '#0C1832'
    red:     '#AC0000'
    green:   '#9c0598'
    yellow:  '#949204'
    blue:    '#9f51c9'
    magenta: '#6f02a3'
    cyan:    '#BE00CD'
    white:   '#a9a9ab'

  # Bright colors
  bright:
    black:   '#F72D93'
    red:     '#e80707'
    green:   '#ff00f8'
    yellow:  '#FFFC04'
    blue:    '#1151F9'
    magenta: '#a005eb'
    cyan:    '#D78FFE'
    white:   '#DCDBE0'
