## Colors configuration
colors:
  # Default colors
  primary:
    background: '#1A1B26'
    foreground: '#D4BFFF'

  # Normal colors
  normal:
    black:   '#171421'
    red:     '#E66D76'
    green:   '#5EDEA3'
    yellow:  '#EFAB73'
    blue:    '#73A3DE'
    magenta: '#D06FE8'
    cyan:    '#75DBEB'
    white:   '#7a7e85'

  # Bright colors
  bright:
    black:   '#6E6C72'
    red:     '#EB867C'
    green:   '#72F0A8'
    yellow:  '#F3D175'
    blue:    '#72A9ED'
    magenta: '#E26FEF'
    cyan:    '#76DBEB'
    white:   '#FFFFFF'
